[2025-07-23T05:09:10.838+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-23T05:09:10.852+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: startup_health_score_full_pipeline.extract_raw_text_from_document manual__2025-07-23T05:09:06.126905+00:00 [queued]>
[2025-07-23T05:09:10.858+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: startup_health_score_full_pipeline.extract_raw_text_from_document manual__2025-07-23T05:09:06.126905+00:00 [queued]>
[2025-07-23T05:09:10.859+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 2
[2025-07-23T05:09:10.866+0000] {taskinstance.py:2907} INFO - Executing <Task(PythonOperator): extract_raw_text_from_document> on 2025-07-23 05:09:06.126905+00:00
[2025-07-23T05:09:10.875+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=56) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-23T05:09:10.883+0000] {standard_task_runner.py:72} INFO - Started process 58 to run task
[2025-07-23T05:09:10.884+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'startup_health_score_full_pipeline', 'extract_raw_text_from_document', 'manual__2025-07-23T05:09:06.126905+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/startup_health_score_dag.py', '--cfg-path', '/tmp/tmp54mzkrdr']
[2025-07-23T05:09:10.887+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask extract_raw_text_from_document
[2025-07-23T05:09:10.922+0000] {task_command.py:467} INFO - Running <TaskInstance: startup_health_score_full_pipeline.extract_raw_text_from_document manual__2025-07-23T05:09:06.126905+00:00 [running]> on host b490a7ec6fe3
[2025-07-23T05:09:10.972+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='startup_health_score_full_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_text_from_document' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T05:09:06.126905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-23T05:09:06.126905+00:00'
[2025-07-23T05:09:10.973+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-07-23T05:09:11.052+0000] {log.py:232} WARNING - 2025-07-23 05:09:11,052 - startup_health_score - INFO - Tesseract OCR engine found (version: 5.3.0).
[2025-07-23T05:09:11.052+0000] {kpi_extractor.py:49} INFO - Tesseract OCR engine found (version: 5.3.0).
[2025-07-23T05:09:11.053+0000] {log.py:232} WARNING - 2025-07-23 05:09:11,053 - startup_health_score - INFO - KPIExtractor initialized.
[2025-07-23T05:09:11.053+0000] {kpi_extractor.py:53} INFO - KPIExtractor initialized.
[2025-07-23T05:09:11.053+0000] {log.py:232} WARNING - 2025-07-23 05:09:11,053 - startup_health_score - INFO - Attempting to extract raw text from: /opt/***/uploads/.DS_Store (Type: )
[2025-07-23T05:09:11.053+0000] {kpi_extractor.py:130} INFO - Attempting to extract raw text from: /opt/***/uploads/.DS_Store (Type: )
[2025-07-23T05:09:11.054+0000] {log.py:232} WARNING - 2025-07-23 05:09:11,054 - startup_health_score - ERROR - Unsupported file type for raw text extraction: 
[2025-07-23T05:09:11.054+0000] {kpi_extractor.py:148} ERROR - Unsupported file type for raw text extraction: 
[2025-07-23T05:09:11.054+0000] {log.py:232} WARNING - 2025-07-23 05:09:11,054 - startup_health_score - ERROR - Raw text extraction failed or returned no content for /opt/***/uploads/.DS_Store. Task will fail.
[2025-07-23T05:09:11.054+0000] {startup_health_score_dag.py:85} ERROR - Raw text extraction failed or returned no content for /opt/***/uploads/.DS_Store. Task will fail.
[2025-07-23T05:09:11.060+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/startup_health_score_dag.py", line 86, in _extract_raw_text
    raise AirflowException("Raw text extraction returned no data.")
airflow.exceptions.AirflowException: Raw text extraction returned no data.
[2025-07-23T05:09:11.067+0000] {taskinstance.py:1242} INFO - Marking task as UP_FOR_RETRY. dag_id=startup_health_score_full_pipeline, task_id=extract_raw_text_from_document, run_id=manual__2025-07-23T05:09:06.126905+00:00, execution_date=20250723T050906, start_date=20250723T050910, end_date=20250723T050911
[2025-07-23T05:09:11.082+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-07-23T05:09:11.083+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task extract_raw_text_from_document (Raw text extraction returned no data.; 58)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/startup_health_score_dag.py", line 86, in _extract_raw_text
    raise AirflowException("Raw text extraction returned no data.")
airflow.exceptions.AirflowException: Raw text extraction returned no data.
[2025-07-23T05:09:11.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-23T05:09:11.125+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-23T05:09:11.126+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
